### ISSUE TITLE
BUG : Converting mutez to tez causes an error when checking the deposit transaction

### ISSUE THREAD

**Issue by quentin-burg** [marigold-dev/gas-station#20]
When I want to deposit 10.000001 tez , API answers with a 404 error code and message `Could not find confirmation for 10000001 with XXXX`
The transaction contains only 10 tez (without the few amount of mutez) and API didn't recognize it .

Example of transaction : https://ghostnet.tzkt.io/onrWnsnGRR4Hdhw2on9hoH417kPQDb6dLnNBrDmHqzvi6eb5ctL/15366718

**Comment by aguillon** [comment]
Fixed?

**Comment by quentin-burg** [comment]
on staging yes 👍
