### ISSUE TITLE
DOCS: Add tutorial for build a permit smart contract

### ISSUE THREAD

**Issue by quentin-burg** [marigold-dev/gas-station#23]
> Tutorial would include a part about Permit from smart contract point of view. Developpers who will use SDK will not know about.

> Minimal here would be to have an anatomy of the smart contract and make devs deploy there own. You can start with the global one and introduce this later, but i think it must be part of the tuto

**Comment by aguillon** [comment]
What do you mean? Should we explain permits in a separate chapter?

**Comment by aguillon** [comment]
I'll do it.

**Comment by quentin-burg** [comment]
Done 👌
